# Generated by Django 2.2.3 on 2019-11-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='computer',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('G', '高端本'), ('K', '开发本'), ('S', '商务本'), ('Q', '轻薄本'), ('Y', '游戏本')], default='Q', max_length=2)),
                ('year', models.IntegerField()),
                ('colors', models.CharField(max_length=64)),
                ('price', models.PositiveIntegerField()),
                ('battery_score', models.FloatField()),
                ('beauty_score', models.FloatField()),
                ('disk_score', models.FloatField()),
                ('price_score', models.FloatField()),
                ('processor_score', models.FloatField()),
                ('screen_score', models.FloatField()),
                ('size_score', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='computerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('src', models.CharField(max_length=128)),
            ],
        ),
    ]
