# Generated by Django 2.2.3 on 2019-11-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='computer_rawdata',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('memory', models.PositiveIntegerField()),
                ('card', models.IntegerField()),
                ('disk', models.PositiveIntegerField()),
                ('cores', models.PositiveIntegerField()),
                ('processor', models.CharField(max_length=16)),
                ('screen', models.CharField(max_length=32)),
                ('battery', models.FloatField()),
            ],
        ),
    ]
