# Generated by Django 2.2.3 on 2019-11-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_score_buffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='score_buffer',
        ),
    ]
